[34m[1mLogs will be synced with wandb.
 [34mtrain[39m   [30mE:[39m 1                [30mS:[39m 0                [30mR:[39m -5.0             [30mT:[39m 0:00:00
 [32meval[39m    [30mE:[39m 1                [30mS:[39m 0                [30mR:[39m -3.3             [30mT:[39m 0:00:00
 [34mtrain[39m   [30mE:[39m 2                [30mS:[39m 1,000            [30mR:[39m -5.0             [30mT:[39m 0:00:04
 [34mtrain[39m   [30mE:[39m 3                [30mS:[39m 2,000            [30mR:[39m 5.6              [30mT:[39m 0:00:04
 [34mtrain[39m   [30mE:[39m 4                [30mS:[39m 3,000            [30mR:[39m -5.0             [30mT:[39m 0:00:04
 [34mtrain[39m   [30mE:[39m 5                [30mS:[39m 4,000            [30mR:[39m -4.8             [30mT:[39m 0:00:04
 [34mtrain[39m   [30mE:[39m 6                [30mS:[39m 5,000            [30mR:[39m 1.8              [30mT:[39m 0:00:04
 [34mtrain[39m   [30mE:[39m 7                [30mS:[39m 6,000            [30mR:[39m -5.0             [30mT:[39m 0:00:04
 [34mtrain[39m   [30mE:[39m 8                [30mS:[39m 7,000            [30mR:[39m -5.0             [30mT:[39m 0:00:04
 [34mtrain[39m   [30mE:[39m 9                [30mS:[39m 8,000            [30mR:[39m -5.0             [30mT:[39m 0:00:04
 [34mtrain[39m   [30mE:[39m 10               [30mS:[39m 9,000            [30mR:[39m -5.0             [30mT:[39m 0:00:04
Traceback (most recent call last):
  File "train.py", line 146, in <module>
    train(parse_cfg(Path().cwd() / __CONFIG__))
  File "train.py", line 114, in train
    train_metrics.update(agent.update(buffer,step+i))
  File "/home/jeongtae/RLMPPI/src/algorithm/tdmpc.py", line 201, in update
    priority_loss += rho * (h.l1(Q1, td_target) + h.l1(Q2, td_target))(1-done[t]) #Î¶¨ÌîåÎ†àÏù¥ Î≤ÑÌçº Ïö∞ÏÑ†ÏàúÏúÑ ÏÑ§Ï†ï
TypeError: 'Tensor' object is not callable